version: '3.6'

networks:
  project:
    driver: bridge

services:

  mysql:
    container_name: my-database
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: direct_search
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
      MYSQL_ROOT_PASSWORD: root
    networks:
      - project

  php:
    container_name: my-app
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ./html:/var/www/html
      - ./logs/php:/var/log/php/
    ports:
      - "8000:80"
    networks:
      - project